language: java

#jdk 버전 바꿔야할수있음.
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      -96bgm@korea.ac.kr
